server {
    listen 80;
    server_name app-k3s.duckdns.org;

    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /var/www/html;
        allow all;
    }
}

server {
    listen 443 ssl;
    server_name app-k3s.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/app-k3s.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app-k3s.duckdns.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:30080;
        
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}